### PR TITLE
Removed jQuery dependency

### PR DESCRIPTION
**Pull request by hdragomir**
I was wondering why this needed to be a jQuery plugin and could not be used with plain ol' vanilla JS.

Have a look at the vanilla JS version, with optional jQuery plugin, if jQuery is available.
Also, my editor cleaned up some whitespace as a bonus.

### CODE REVIEW

**Comment by okiii** [comment]
This pull request resulted in big CPU consumption changes. The current master is about 70-80% CPU on my test page and this revised version is only 15%.

Nice work @hdragomir :)

**Comment by jnicol** [comment]
I guess I really need to merge this then!

**Comment by okiii** [comment]
I just done more testing in different browsers and it looks like the performance benifits are mostly Google Chrome. Firefox was slightly less than before, but still high CPU usage.

Memory use is effected too - these changes result in far less mem consumption.

**Comment by jnicol** [comment]
I have merged this PR and fixed a couple of bugs/omissions:

- Particles were not bouncing off bottom of screen, so were being lost from the canvas.
- It seemed to me that public methods (pause, start, destroy) were no longer available in the vanilla JS version.  I modified Particleground to return the plugin instance, which can then have methods called on it.

I definitely notice the performance improvements in Chrome. Not so much in Firefox.

Great work @hdragomir, and sorry it took me so long to give this a proper look.

**Pull request closed without merging**
